FROM oven/bun AS build
WORKDIR /app
COPY package.json .
COPY tsconfig.json .
COPY bun.lockb .
COPY ./apps ./apps
RUN bun install
RUN bun run build:web

FROM node:20-alpine
WORKDIR /app
EXPOSE 3000
COPY --from=build /app/apps/planning-poker-web/build ./build
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/apps/planning-poker-web/package.json .
CMD [ "node", "build" ]
