FROM oven/bun
WORKDIR /app

COPY package.json .
COPY tsconfig.json .
COPY apps/planning-poker-api  ./apps/planning-poker-api
COPY bun.lockb .

RUN bun install

ENV NODE_ENV production
CMD ["bun", "--version", ";bun", "apps/planning-poker-api/src/index.ts"]

EXPOSE 3001