FROM oven/bun AS builder
WORKDIR /app
COPY package.json .
COPY tsconfig.json .
COPY apps/planning-poker-api  ./apps/planning-poker-api
COPY apps/planning-poker-web  ./apps/planning-poker-web
COPY bun.lockb .
RUN bun install
RUN cd ./apps/planning-poker-web && bun run build

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/apps/planning-poker-web/build build/
COPY --from=builder /app/node_modules node_modules/
COPY apps/planning-poker-web/package.json .
EXPOSE 3000
ENV NODE_ENV=production
CMD [ "node", "build" ]
