FROM oven/bun AS build
WORKDIR /app
COPY package.json .
COPY tsconfig.json .
COPY bun.lockb .
COPY ./apps ./apps
RUN bun install
CMD [ "/bin/sh" , "-c" , "cd ./apps/planning-poker-web && bun run build" ]



FROM node:20-alpine
WORKDIR /app
EXPOSE 3000
COPY --from=build /app/apps/planning-poker-web/build ./build
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/apps/planning-poker-web/package.json .
CMD [ "node", "build" ]
